
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 30 00:32:41 EDT 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RIGHT_PAREN = 27;
  public static final int RIGHT_BRACKET = 26;
  public static final int ASSIGNMENT = 3;
  public static final int INT = 12;
  public static final int MINUS = 18;
  public static final int STATIC = 29;
  public static final int NOT = 21;
  public static final int SEMICOLON = 28;
  public static final int AND = 2;
  public static final int COMMA = 6;
  public static final int LEFT_BRACE = 13;
  public static final int CLASS = 5;
  public static final int DEREFERENCE = 7;
  public static final int PLUS = 22;
  public static final int MULTIPLY = 19;
  public static final int MAIN = 17;
  public static final int IF = 11;
  public static final int THIS = 30;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int RETURN = 24;
  public static final int TRUE = 31;
  public static final int NEW = 20;
  public static final int error = 1;
  public static final int RIGHT_BRACE = 25;
  public static final int VOID = 32;
  public static final int ELSE = 8;
  public static final int WHILE = 33;
  public static final int PUBLIC = 23;
  public static final int EXTENDS = 9;
  public static final int LEFT_PAREN = 15;
  public static final int STRING = 36;
  public static final int FALSE = 10;
  public static final int LESS_THAN = 16;
  public static final int LEFT_BRACKET = 14;
  public static final int LENGTH = 35;
  public static final int PRINT = 34;
  public static final int INT_LITERAL = 38;
  public static final int IDENTIFIER = 37;
}

